volumes:
  minecraft-gius-family-server-data:
  minecraft-bluemap-web:
    

services:
  minecraft-gius-family-server:
    image: itzg/minecraft-bedrock-server:2025.11.0
    container_name: minecraft-gius-family-server
    environment:
      EULA: "TRUE"
      GAMEMODE: "survival"
      DIFFICULTY: "peaceful"
      ALLOW_CHEATS: "false"
      MAX_PLAYERS: 10
      SERVER_NAME: "Gius Family Server"
      SERVER_PORT: 19132
      LEVEL_NAME: "BedrockWorld"
      ONLINE_MODE: "true"
      VIEW_DISTANCE: 10
      TICK_DISTANCE: 10
      WHITE_LIST: "false"
      DOWNLOAD_DIR: /data/downloads
      ENABLE_LAN_VISIBILITY: "true"
      CHAT_RESTRICTION: "Disabled"
      ENABLE_SSH: "true"
      
      # DEFAULT_PLAYER_PERMISSION_LEVEL
      # SERVER_AUTHORITATIVE_MOVEMENT
      # CORRECT_PLAYER_MOVEMENT

    ports:
      - "19132:19132/udp"
    volumes:
      - type: volume
        source: minecraft-gius-family-server-data
        target: /data
    restart: unless-stopped
  
  minecraft-backup:
    image: kaiede/minecraft-bedrock-backup
    restart: unless-stopped
    depends_on:
      minecraft-gius-family-server:
        condition: "service_healthy"
    environment:
      TZ: "America/Los_Angeles"
    volumes:
      - type: volume
        source: synology_shared
        target: /data
        volume: 
          subpath: minecraft/backups
      - type: volume
        source: minecraft-gius-family-server-data
        target: /source
      - type: bind
        source: ./backup/config.yml
        target: /data/config.yml
        read_only: true

  minecraft-bluemap:
    build:
      dockerfile: ./Dockerfile.bluemap
      target: chunker
    volumes:
      - type: volume
        source: synology_shared
        target: /backups
        volume: 
          subpath: minecraft/backups
      - type: bind
        source: ./bluemap/config
        target: /output/config
      - type: bind
        source: ./bluemap/data
        target: /output/data
      - type: volume
        source: minecraft-bluemap-web
        target: /output/web
    environment:
      BACKUP_FOLDER: /backups
      WORLD_FOLDER: /output/world