networks:
  meet.jitsi:

services:
  jitsi-web:
    image: jitsi/web:${JITSI_IMAGE_VERSION:-unstable}
    restart: ${RESTART_POLICY:-unless-stopped}
    # ports:
    #   - '${HTTP_PORT}:80'
    #   - '${HTTPS_PORT}:443'
    volumes:
      - ${CONFIG}/web:/config:Z
      - ${CONFIG}/web/crontabs:/var/spool/cron/crontabs:Z
      - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
      - ${CONFIG}/web/load-test:/usr/share/jitsi-meet/load-test:Z
    labels:
      service: "jitsi-web"
    env_file: 
      - ./jitsi.env
      - ./jitsi-passwords.env
    networks:
      meet.jitsi:
      default:
    depends_on:
      - jvb
      - jicofo
      - prosody

  # XMPP server
  prosody:
    image: jitsi/prosody:${JITSI_IMAGE_VERSION:-unstable}
    restart: ${RESTART_POLICY:-unless-stopped}
    # expose:
    #   - '${XMPP_PORT:-5222}'
    #   - '${PROSODY_S2S_PORT:-5269}'
    #   - '5347'
    #   - '${PROSODY_HTTP_PORT:-5280}'
    env_file: 
      - ./jitsi.env
      - ./jitsi-passwords.env
    labels:
      service: "jitsi-prosody"
    volumes:
      - ${CONFIG}/prosody/config:/config:Z
      - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
    networks:
      default:
      meet.jitsi:
        # aliases:
        #   - ${XMPP_SERVER:-xmpp.meet.jitsi}

  # Focus component
  # jitsi-conference-focus
  jicofo:
    image: jitsi/jicofo:${JITSI_IMAGE_VERSION:-unstable}
    restart: ${RESTART_POLICY:-unless-stopped}
    # ports:
    #   - '127.0.0.1:${JICOFO_REST_PORT:-8888}:8888'
    volumes:
      - ${CONFIG}/jicofo:/config:Z
    labels:
      service: "jitsi-jicofo"
    env_file: 
      - ./jitsi.env
      - ./jitsi-passwords.env
    depends_on:
      - prosody
    networks:
      meet.jitsi:

  # Video bridge
  # jitsi-videobridge
  jvb:
    image: jitsi/jvb:${JITSI_IMAGE_VERSION:-unstable}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '${JVB_PORT:-10000}:${JVB_PORT:-10000}/udp'
    #   - '127.0.0.1:${JVB_COLIBRI_PORT:-8080}:8080'
    volumes:
      - ${CONFIG}/jvb:/config:Z
    labels:
      service: "jitsi-jvb"
    env_file: 
      - ./jitsi.env
      - ./jitsi-passwords.env
    depends_on:
      - prosody
    networks:
      meet.jitsi:
